// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-JjbG5o0IPMkHqiepWIuhHrTrmDlFoKU',
    appId: '1:819507712444:web:4d17f8f4d04f2dcc1a9bb9',
    messagingSenderId: '819507712444',
    projectId: 'safe-crop',
    authDomain: 'safe-crop.firebaseapp.com',
    databaseURL: 'https://safe-crop-default-rtdb.firebaseio.com',
    storageBucket: 'safe-crop.appspot.com',
    measurementId: 'G-ER7KC75RZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUgP34xVNOtX4-R0B4yVVoWyJX30Pwf6E',
    appId: '1:819507712444:android:1a4d7069e922de341a9bb9',
    messagingSenderId: '819507712444',
    projectId: 'safe-crop',
    databaseURL: 'https://safe-crop-default-rtdb.firebaseio.com',
    storageBucket: 'safe-crop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2k6B1qp12T5FNSdA1n0JWN-uzDDUB_Sg',
    appId: '1:819507712444:ios:d5df50ac4075b8de1a9bb9',
    messagingSenderId: '819507712444',
    projectId: 'safe-crop',
    databaseURL: 'https://safe-crop-default-rtdb.firebaseio.com',
    storageBucket: 'safe-crop.appspot.com',
    iosBundleId: 'com.example.safeCrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2k6B1qp12T5FNSdA1n0JWN-uzDDUB_Sg',
    appId: '1:819507712444:ios:f88ad8051f5b4b681a9bb9',
    messagingSenderId: '819507712444',
    projectId: 'safe-crop',
    databaseURL: 'https://safe-crop-default-rtdb.firebaseio.com',
    storageBucket: 'safe-crop.appspot.com',
    iosBundleId: 'com.example.safeCrop.RunnerTests',
  );
}
